### ISSUE TITLE
manuf -u throws exception with 403 Forbidden

### ISSUE THREAD

**Issue by solsticedhiver** [daniel-leicht/manuf-ng#3]
```
$ manuf -u -m ./manuf
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/manuf/manuf.py", line 142, in update
    response = urlopen(manuf_url)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/manuf", line 11, in <module>
    load_entry_point('manuf==1.0.0', 'console_scripts', 'manuf')()
  File "/usr/lib/python3.8/site-packages/manuf/manuf.py", line 322, in main
    parser = MacParser(manuf_name=args.manuf, update=args.update)
  File "/usr/lib/python3.8/site-packages/manuf/manuf.py", line 68, in __init__
    self.update()
  File "/usr/lib/python3.8/site-packages/manuf/manuf.py", line 144, in update
    raise URLError("Failed downloading OUI database")
urllib.error.URLError: <urlopen error Failed downloading OUI database>

```

**Comment by solsticedhiver** [comment]
This works by setting a User-agent instead of the default one. Even an old user-agent works.

    --- manuf/manuf.py	2020-07-21 20:35:53.125024597 +0200
    +++ manuf/manuf.py	2020-07-21 20:38:05.087109376 +0200
    @@ -27,8 +27,9 @@
     try:
         from urllib2 import urlopen
         from urllib2 import URLError
    +    from urllib2 import Request
     except ImportError:
    -    from urllib.request import urlopen
    +    from urllib.request import urlopen, Request
         from urllib.error import URLError
     
     try:
    @@ -38,6 +39,7 @@
     import importlib
     import os
     
    +FAKE_USER_AGENT = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
     # Vendor tuple
     Vendor = namedtuple('Vendor', ['manuf', 'manuf_long', 'comment'])
     
    @@ -139,7 +141,9 @@
     
             # Retrieve the new database
             try:
    -            response = urlopen(manuf_url)
    +            req = Request(manuf_url)
    +            req.add_header('User-Agent', FAKE_USER_AGENT)
    +            response = urlopen(req)
             except URLError:
                 raise URLError("Failed downloading OUI database")
     
    @@ -159,7 +163,9 @@
     
             # Append WFA to new database
             try:
    -            response = urlopen(wfa_url)
    +            req = Request(wfa_url)
    +            req.add_header('User-Agent', FAKE_USER_AGENT)
    +            response = urlopen(req)
             except URLError:
                 raise URLError("Failed downloading WFA database")

**Comment by tristanlatr** [comment]
Thanks ! The now updated repository is https://github.com/coolbho3k/manuf
